language: ruby
sudo: required
services:
  - docker

rvm:
  - ruby-head
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - 2.3
matrix:
  allow_failures:
  - rvm: ruby-head
install:
  - bundle install --without development
script:
  - docker run -itd -p 80:80 onlyoffice/documentserver
  - sleep 60
  - bundle exec rspec --fail-fast
